routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('project.index');
});

Auth::routes(['register' => false]);

Route::middleware(['auth'])->group(
    function () {
        Route::prefix('project')->group(
            function () {
                Route::get('/', 'ProjectController@index')->name('project.index');
                Route::get('/my-projects', 'ProjectController@owner')->name('project.owner');
                Route::get('/create', 'ProjectController@create')->name('project.create');
                Route::post('/', 'ProjectController@store')->name('project.store');
                Route::get('/{project}/edit', 'ProjectController@edit')->name('project.edit');
                Route::patch('/{project}', 'ProjectController@update')->name('project.update');
                Route::delete('/{project}', 'ProjectController@destroy')->name('project.destroy');
                Route::get('/export/{project}', 'ZipController@export')->name('project.export');
                // live-search
                Route::post('/{project}/set-search', 'CredentialsSetController@search')->name('set.search');

                Route::prefix('/{project}/access')->group(
                    function () {
                        Route::get('/', 'AccessRightGrantController@index')->name('access.index');
                        Route::delete('/{access}', 'AccessRightGrantController@destroy')->name('access.destroy');
                        Route::post('/', 'AccessRightGrantController@store')->name('access.store');
                        Route::get('/{access}/edit', 'AccessRightGrantController@edit')->name('access.edit');
                        Route::post('/{access}', 'AccessRightGrantController@update')->name('access.update');
                    }
                );
            }
        );
        Route::resource('project.sets', 'CredentialsSetController');

        Route::get('/my-profile', 'UserController@profile')->name('user.profile');
        Route::get('/all-users', 'UserController@all')->name('user.all');

        Route::get('/panic', 'ProjectController@panic')->name('project.panic');
    }
);

resources/views/sets/create.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
{{--    <h2 class="m-0 text-dark">Create set</h2>--}}
@stop

@section('content')
    <section class="content">

        <!-- Default box -->
        <div class="row">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Set creation</h3>
                    </div>
                    <form method="POST" action="{{ route('project.sets.index', $project->id) }}">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Set Name</label>
                                <input type="text" name="name" id="inputName"
                                       class="form-control @error('name') is-invalid @enderror"
                                       value="{{ old('name') }}">
                            </div>
                            @error('name')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                            <div class="form-group">
                                <label for="inputDescription">Text</label>
                                <textarea name="set_text" id="inputDescription"
                                          class="form-control @error('set_text') is-invalid @enderror"
                                          rows="4">{{ old('set_text') }}</textarea>
                            </div>
                            @error('set_text')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <div class="row">
                                <div class="col-12">
                                    <a href="{{ route('project.index') }}" class="btn btn-secondary">Cancel</a>
                                    <input type="submit" value="Create new Set" name="addSet"
                                           class="btn btn-success float-right">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.card -->
        </div>

    </section>
    <!-- /.content -->
@stop

resources/views/sets/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Set editing</h1>
@stop

@section('content')
    <section class="content">

        <!-- Default box -->
        <div class="row">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Fill in the fields</h3>
                    </div>
                    <form method="POST" action="{{ route('project.sets.update', [$project->id, $set['id']]) }}">
                        @method('PATCH')
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Set Name</label>
                                <input type="text" name="name" id="inputName"
                                       class="form-control @error('name') is-invalid @enderror"
                                       value="{{old('name') ?? $set['name'] }}">
                            </div>
                            @error('name')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                            <div class="form-group">
                                <label for="inputDescription">Text</label>
                                <textarea name="set_text" id="inputDescription"
                                          class="form-control @error('set_text') is-invalid @enderror"
                                          rows="4">{{ old('set_text') ?? $set['set_text'] }}</textarea>
                            </div>
                            @error('set_text')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <div class="row">
                                <div class="col-12">
                                    <a href="{{ route('project.sets.index', $project->id) }}" class="btn btn-secondary">Cancel</a>
                                    <input type="submit" value="Edit set" name="editSet"
                                           class="btn btn-success float-right">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.card -->
        </div>

    </section>
    <!-- /.content -->
@stop

resources/views/sets/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    {{--    <h1 class="m-0 text-dark">{{ $project->project_name }}</h1>--}}
@stop

@section('content')
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <h3 class="card-header">{{ $project->project_name }}</h3>
            <div class="card-body">
                <p class="card-text">{{ $project->description }}</p>
                @can('update', $project)
                    <a href="{{ route('access.index', $project->id) }}" class="btn bg-gradient-secondary btn-sm"><i
                            class="fas fa-key"></i> Access</a>
                @endcan
            </div>
        </div>
        <div>
            <input type="text" id="search-set" class="form-control" placeholder="Start typing name to search set">
        </div>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Credentials: {{ $sets->count() }} sets</h3>
                @if ($sets->count() > 0)
                    <a href="{{ route('project.export', $project->id) }}" target="_blank"
                       class="btn-link text-secondary" style="margin-left: 25px"><i
                            class="fas fa-download"></i> Generate PDF</a>
                @endif
                <div class="card-tools">
                    <div class="row">
                        @can('createSet', $project)
                            <div class="col-12 text-right">
                                <a href="{{ route('project.sets.create', $project->id) }}"><input type="submit"
                                                                                                  value="Add new Set"
                                                                                                  class="btn btn-success float-right"></a>
                            </div>
                        @endcan
                    </div>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Set</th>
                        <th style="width: 200px">Action</th>
                    </tr>
                    </thead>
                    <tbody id="dynamic-row">
                    @foreach($sets as $set)
                        <tr>
                            <td>{{ $loop->iteration }}.</td>
                            <td>
                                <p><b><i>{{ $set['name'] }}</i></b></p>
                                <p>{{ $set['set_text'] }}</p>
                            </td>

                            <td>
                                @can('updateSet', $project)
                                    <a class="btn btn-info btn-sm" style="width: 67.5px; margin-bottom: 10px"
                                       href="{{ route('project.sets.edit', [$project->id, $set['id']]) }}">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </a>
                                @endcan
                                @can('deleteSet', $project)
                                    <form method="post"
                                          action="{{ route('project.sets.destroy', [$project->id, $set['id']]) }}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" value="Delete" class="btn btn-danger btn-sm"><i
                                                class="fas fa-trash"></i>Delete
                                        </button>
                                    </form>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->

        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@stop
@section('js')
    <script type="text/javascript">
        $('body').on('keyup', '#search-set', function () {
            var searchQuest = $(this).val();
            $.ajax({
                method: 'POST',
                url: '{{ route("set.search", $project->id) }}',
                //dataType: 'json',
                data: {
                    '_token': '{{ csrf_token() }}',
                    searchQuest: searchQuest
                },
                success: function (response) {
                    $('#dynamic-row').html(response);
                }
            })
        })
    </script>
@stop

resources/views/sets/set-search.blade.php
@foreach($sets as $set)
    <tr>
        <td>{{ $loop->iteration }}.</td>
        <td>
            <p><b><i>{{ $set['name'] }}</i></b></p>
            <p>{{ $set['set_text'] }}</p>
        </td>

        <td>
            @can('updateSet', $project)
                <a class="btn btn-info btn-sm" style="width: 67.5px; margin-bottom: 10px"
                   href="{{ route('project.sets.edit', [$project->id, $set['id']]) }}">
                    <i class="fas fa-pencil-alt"></i>Edit
                </a>
            @endcan
            @can('deleteSet', $project)
                <form method="post"
                      action="{{ route('project.sets.destroy', [$project->id, $set['id']]) }}">
                    @method('DELETE')
                    @csrf
                    <button type="submit" value="Delete" class="btn btn-danger btn-sm">
                        <i class="fas fa-trash"></i>Delete
                    </button>
                </form>
            @endcan
        </td>
    </tr>
@endforeach